"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
"""

def findTheDifference(s, t):
        """
        :type    s: str
        :type t: str
        :rtype: str
        """
        l = [s, t]
        spl = ''.join(l)
        a = 0
        for i in spl:
            asci = ord(i) 
            a ^= asci
        return chr(a)

print(findTheDifference('sda', 'asde'))